$(function(){
    $('#home').hover(function(){
        $(this).toggleClass('text-light');
    });
    $('#events').hover(function(){
        $(this).toggleClass('text-light');
    });
    $('#iris').hover(function(){
        $(this).toggleClass('text-light');
    });
    $('#voyager').hover(function(){
        $(this).toggleClass('text-light');
    });
    $('#about').hover(function(){
        $(this).toggleClass('text-light');
    });
    $('#team').hover(function(){
        $(this).toggleClass('text-light');
    });
    $('#blog').hover(function(){
        $(this).toggleClass('text-light');
    });
})